"""
Generate paper-to-code alignment reports on releases.
Creates a Markdown report showing which equations have implementations.
"""
from app.models.paper import Paper
from app.models.equation_mapping import EquationMapping
from sqlalchemy import select
from datetime import datetime


async def generate_release_report(db, repo_id: int, version: str, owner: str, repo_name: str) -> str:
    """
    Generate a Markdown paper implementation coverage report.
    Called when a new GitHub Release is published.
    """
    # Fetch all papers linked to this repo
    papers_result = await db.execute(
        select(Paper).where(Paper.repository_id == repo_id)
    )
    papers = papers_result.scalars().all()

    # Fetch all equation mappings for this repo
    mappings_result = await db.execute(
        select(EquationMapping).where(EquationMapping.repository_id == repo_id)
    )
    mappings = mappings_result.scalars().all()

    # Index mappings by equation label
    implemented: set[str] = {m.equation_label for m in mappings}

    lines = [
        f"# 📐 Paper Implementation Report — {version}",
        f"*Generated by [GitPaper](https://gitpaper.dev) on {datetime.utcnow().strftime('%Y-%m-%d')}*",
        "",
        "---",
        "",
    ]

    total_equations = 0
    total_implemented = 0

    for paper in papers:
        paper_equations = paper.equations or []
        total_equations += len(paper_equations)

        paper_implemented = [eq for eq in paper_equations if eq in implemented]
        total_implemented += len(paper_implemented)
        coverage = len(paper_implemented) / len(paper_equations) * 100 if paper_equations else 0

        lines.extend([
            f"## 📄 {paper.title}",
            f"- **arXiv:** [{paper.arxiv_id}]({paper.pdf_url})" if paper.arxiv_id else "",
            f"- **Authors:** {', '.join(paper.authors[:3])}" if paper.authors else "",
            f"- **Coverage:** {len(paper_implemented)}/{len(paper_equations)} equations ({coverage:.0f}%)",
            "",
            "| Equation | Implemented | File |",
            "|---|---|---|",
        ])

        for eq_label in paper_equations:
            matching_mappings = [m for m in mappings if m.equation_label == eq_label]
            if matching_mappings:
                m = matching_mappings[0]
                lines.append(f"| `{eq_label}` | ✅ | `{m.file_path}` |")
            else:
                lines.append(f"| `{eq_label}` | ❌ | *Not implemented* |")

        lines.append("")

    # Summary
    overall_coverage = total_implemented / total_equations * 100 if total_equations else 0
    lines.extend([
        "---",
        "",
        "## 📊 Overall Coverage",
        f"**{total_implemented}/{total_equations} equations implemented ({overall_coverage:.0f}%)**",
        "",
        f"*Tracked by [GitPaper](https://gitpaper.dev) — link code to research papers*",
    ])

    return "\n".join(lines)
